- name: URL Health Check
  uses: Jtalk/url-health-check-action@v1.5
  with: 
    url: https://secret-beach-26488.herokuapp.com/
  on:
    push:
      branches: [my-branch]
      #schedule:
    # * is a special character in YAML so you have to quote this string
      #- cron:  '30 5,17 * * *'

