name: Periodic health check

on:
  push:
    branches: [ my-branch ]

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v1.5
        with: 
          url: https://secret-beach-26488.herokuapp.com/
      #schedule:
    # * is a special character in YAML so you have to quote this string
      #- cron:  '30 5,17 * * *'

